### ISSUE TITLE
Métodos de entrada melhorado

### ISSUE THREAD

**Issue by ImMarcio** [AllanSmithll/Sistema-Estacionamento-POO#6]
import java.io.File;
import java.io.FileWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Scanner;

/**

TSI - POO - Allan Amâncio, Márcio José, Yuri Sousa
Classe Estacionamento
*/

		
// As propriedades precisam ser melhoradas
public class Estacionamento {
private String[] placas;

// Queria saber se as propriedades e o construtor estão corretos
public Estacionamento(int vagasTotais) throws Exception {
	if(vagasTotais <= 0) {
		throw new Exception("Quantidade de vagas inválida. Tem que ter pelo menos uma vaga.");
	}
	

	placas = new String[vagasTotais];
	for(int i=0; i<placas.length; i++) {
		placas[i] = "livre";
	}
}

//registrar placa no estacionamento e na sua determinada vaga.
public void entrar(String placa, int vaga)  throws Exception {
	

	if(vaga < 1 || vaga > this.placas.length) {
		throw new Exception(" A vaga está fora  do limite 1 a " + this.placas.length);
	}
	if(!this.placas[vaga - 1].equals("livre") ) {
		throw new Exception("A vaga já está ocupada. Verifique as vagas livre!");
	}
	else {
		
		DateTimeFormatter pattern;
		pattern = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
		LocalDateTime agora = LocalDateTime.now();
		FileWriter historico = new FileWriter(new File("historico.csv"), true); 
		
		this.placas[vaga - 1] = placa;
		String str = String.valueOf(vaga -1);
		historico.write(agora.format(pattern) + ";" + str + ";" + this.placas[vaga - 1] + ";" + "entrada" +"\n");
		historico.close();
		
	}
	
}

//remove registro da placa do estacionamento
public void sair(int vaga) throws Exception {
	
	if(!this.placas[vaga - 1].equals("livre")) {		
		DateTimeFormatter pattern;
		pattern = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
		LocalDateTime agora = LocalDateTime.now();	
		FileWriter historico = new FileWriter(new File("historico.csv"), true); 
		String str = String.valueOf(vaga -1);
		historico.write(agora.format(pattern) + ";" + str + ";" + this.placas[vaga - 1] + ";" + "saida" +"\n");
		historico.close();
		
		placas[vaga - 1] = "livre";
	}
	else {
		throw new Exception("A vaga está livre e não pode ser desocupada!");
	}
	
	
}
// transferir carro de uma vaga para outra.
public void transferir(int origem, int destino) {
	if(placas[destino - 1].equals("livre")) {
		String variavelAuxiliar = placas[origem - 1];
		placas[origem - 1] = "livre";
		placas[destino - 1] = variavelAuxiliar;
		
	}
}

// Tratar a exceção de não encontrar a placa

//Método para encontrar a posição da placa consultada
public int consultarPlaca(String placa) {
	int getIndex = Arrays.asList(this.placas).indexOf(placa);
	if (this.placas[getIndex].equals("livre")) {
		return - 1;
	}
	return getIndex + 1;
	
}

public String[] listarGeral() {
	return Arrays.copyOf(placas, placas.length);
//	String[] respose = new  String[this.placas.length];
//
//	for(int i=0; i<placas.length; i++) {
//		respose[i] = this.placas[i] ;
//	}
//	
//	return respose;
}

public ArrayList<Integer> listarLivres(){	
    ArrayList<Integer> vagasLivres = new ArrayList<>();

    for(int i = 0; i < this.placas.length; i++){
        if(this.placas[i].equals("livre")){
        vagasLivres.add(i+1);
        }   
    }
	return vagasLivres;
}

public void gravarDados() throws Exception{
	FileWriter placas = new FileWriter(new File("placas.csv"), true); 
	
	for(int i=0; i < this.placas.length; i++) {
		
		if(!this.placas.equals("livre")) {
			String str = String.valueOf(i);
			placas.write(str + ";" + this.placas[i] + "\n");
			
		}
		placas.close();	
	}
	
}

public lerDados() {
	
}

@Override
public String toString() {
	return "Estacionamento [placas=" + Arrays.toString(placas) + "]";
}
}

**Comment by AllanSmithll** [comment]
Muito bom esse código
